name: Benchmark

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Build
      run: ./mvnw clean package --no-transfer-progress
    - name: Benchmark
      run: java -jar target/microbenchmarks.jar Cipher
